export const AUTH_SET_AUTHENTICATED = 'AUTH_SET_AUTHENTICATED';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_GET_USER_PROFILE = 'AUTH_GET_USER_PROFILE';
export const AUTH_CHECK = 'AUTH_CHECK';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
